online_store/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_store/shop/urls.py
from django.urls import path
from .views import ProductList, ProductDetail

app_name = 'shop'

urlpatterns = [
    path('', ProductList.as_view(), name='product_list'),
    path('<int:pk>', ProductDetail.as_view(), name='product_detail'),
]

online_store/shop/models.py
from django.db import models


class Product(models.Model):
    title = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    def __str__(self):
        return self.title

online_store/shop/views.py
from django.views.generic import ListView, DetailView
from .models import Product


class ProductList(ListView):
    model = Product
    template_name = 'shop/product/list.html'
    context_object_name = 'products_list'


class ProductDetail(DetailView):
    template_name = 'shop/product/detail.html'
    model = Product

online_store/shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

online_store/shop/templates/shop/product/detail.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Product{% endblock %} </h1>
{% endblock %}

{% block content %}
        <a>
            <img src="{{ product.image.url }}" width="225" height="225" alt="">
        </a>
        <h3>{{ product.title }}</h3>
        <p>{{ product.description }}</p>
        <p>Стоимость товара: {{ product.price }}$</p>
        <a href="{% url 'shop:product_list' %}">Back</a>
{% endblock %}

online_store/shop/templates/shop/product/list.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Products{% endblock %}</h1>
{% endblock %}

{% block content%}
    <h1>Наши популярные товары</h1>
        {% for product in products_list %}
        <a>
            <img src="{{ product.image.url }}" width="225" height="225" alt="">
        </a>
        <h3>{{ product.title }}</h3>
        <p>{{ product.description }}</p>
        <p><a href="{% url 'shop:product_detail' product.pk %}">Посмотреть товар</a></p>
        {% endfor %}
{% endblock %}